### ISSUE TITLE
Not able to install the bundle on akeneo 5 

### ISSUE THREAD

**Issue by Geetapukale** [flagbit/akeneo-reference-entity-table-bundle#23]
Hello,
I tried to setup the akaneo 5.0.12 locally and tred to install using the command composer require flagbit/akeneo-reference-entity-table-bundle, which gave the attached error.
Kindly guide me further as what I am missing.

![Screenshot from 2021-04-08 18-09-37](https://user-images.githubusercontent.com/82199022/114136124-db7b5780-9927-11eb-874d-844bc684c64f.png)

**Comment by flagbird** [comment]
Hi @Geetapukale. This is simply because there isn't a release yet for Akeneo 5, but we're already on it.

**Comment by Geetapukale** [comment]
Thank You @flagbird for the update, will be waiting for the next release :)

**Comment by flagbird** [comment]
The first release for Akeneo 5 is done.
